### ISSUE TITLE
Secure API KEY with environment variable

### ISSUE THREAD

**Issue by htanameh** [BHARATH-RANGANATHAN/Portfolio#1]
https://github.com/BHARATH-RANGANATHAN/Portfolio/blob/9946e02e5c4b451eef5270180963d0bf753dbd65/mail.js#L6

@BHARATH-RANGANATHAN , get the `api_key` and `domain` from `process.env`.

**Comment by BHARATH-RANGANATHAN** [comment]
lol paakave ila da 😂
